services:
  - type: worker
    name: cineplex-ticket-bot
    env: python
    buildCommand: echo "Building bot..."
    startCommand: python main.py
    envVars:
      - key: SENDER_EMAIL
        value: ttasfique323162@gmail.com
      - key: RECIPIENT_EMAIL
        value: pkm.tasfique.tanveer@g.bracu.ac.bd
      - key: CHECK_INTERVAL_SECONDS
        value: "30"
      - key: GMAIL_APP_PASSWORD
        sync: false
